### ISSUE TITLE
start / stop

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microbit-robot#41]
detect that the simulator restarted and reset the robot state. If needed the robot can send a start event.

**Comment by eanders-ms** [comment]
The sim isn't always sending the needed messages. We get start/stop from user pressing the toolbar buttons, but not from recompile.

**Comment by pelikhan** [comment]
There is now a "id" field on the message which is unique per run of the simulator. Use this to detect that you need to reset the world.
