### ISSUE TITLE
Microcode not receiving line events

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microbit-robot#65]
LEDs on the robot micro:bit show that line is being detected, but MicroCode not getting the events. Need to figure out where the problem is. MicroCode is getting wall event from robot.

**Comment by tballmsft** [comment]
MicroCode built against old version of microbit-robot - updating.

**Comment by tballmsft** [comment]
Ah. you generalize linestate, which I think may have changed the event codes sent over the radio
```
        /**
         * Line sensor state change
         */
        LineState = 0xfffff30,
        LineLeft = LineState | RobotLineState.Left,
        LineRight = LineState | RobotLineState.Right,
        LineBoth = LineState | RobotLineState.Both,
        LineNone = LineState | RobotLineState.None,
        LineLostLeft = LineState | RobotLineState.LostLeft,
        LineLostRight = LineState | RobotLineState.LostRight,

        LineAnyState = 0xfffff50,
        LineLeftRightState = 0xfffff60,
        LineLeftRightMiddleState = 0xfffff70,
        LineOuterLeftLeftRightOuterRightState = 0xfffff80,
```

**Comment by tballmsft** [comment]
Old logic is in radio.ts: handleLineDetected, which is only called once (on start of radio).

**Comment by tballmsft** [comment]
https://github.com/microsoft/microbit-robot/commit/225096e962098bcc27c69ba7af513df78f265dc1

**Comment by tballmsft** [comment]
line lost logic was incorrect. fixed here: https://github.com/microsoft/microbit-robot/commit/a7c71464ef26266b796db961e005d06e74981abb

**Comment by tballmsft** [comment]
Left and Right mixup probably on MicroCode side.

**Comment by pelikhan** [comment]
Maybe.. I think it was messed up on the hardware side on the cutebot

**Comment by tballmsft** [comment]
Well, the LEDs on the screen looked fine. I think the problem is that Left/Right got swapped in meaning between the events sent over radio and the new code that generalizes the robot line detector. I will test with other robots. The fix is local right now: https://github.com/microsoft/microbit-robot/commit/22b09020f667abe82c84d5c203e2ecc8656c5431

**Comment by tballmsft** [comment]
@pelikhan - I assume that left/right is relative to the robot looking forward, not to us look at the robot face on. Correct?

**Comment by pelikhan** [comment]
Yes robot looking forward.
________________________________

**Comment by tballmsft** [comment]
https://github.com/microsoft/microbit-robot/pull/66
